# Keep the yarn release in .yarn/releases as this keeps yarn-contrib/plugin-production-install used
# by our functions deploy script to generate a workspace specific stripped down yarn.lock working
# out of the box (otherwise we would need to manually it).
yarnPath: ".yarn/releases/yarn-1.23.0-20210103.1434.cjs"
